version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    restart: always

  analyzer:
    build: ./audio-analyzer
    ports:
      - "5000:5000"
    volumes:
      - ./audio-analyzer:/app
    restart: always
